CREATE TABLE product (
    id int primary key generated by default as identity,
    product_name varchar (255) not null,
    calories int
);

CREATE TABLE product_in_stock (
    id int primary key generated by default as identity,
    product_id int references product(id),
    quantity int,
    recommended_quantity int
);

CREATE TABLE stock_change (
    id int primary key generated by default as identity,
    product_id int references product(id),
    change int,
    timestamp timestamp
);

INSERT INTO product (calories, product_name) VALUES (10, 'water');
INSERT INTO product (calories, product_name) VALUES (200, 'bread');
INSERT INTO product (calories, product_name) VALUES (50, 'tomato');
INSERT INTO product (calories, product_name) VALUES (70, 'potato');
INSERT INTO product (calories, product_name) VALUES (10, 'coffee');

INSERT INTO product_in_stock (quantity, product_id, recommended_quantity) VALUES (3, 1, 15);
INSERT INTO product_in_stock (quantity, product_id, recommended_quantity) VALUES (30, 2, 10);
INSERT INTO product_in_stock (quantity, product_id, recommended_quantity) VALUES (10, 3, 10);
INSERT INTO product_in_stock (quantity, product_id, recommended_quantity) VALUES (11, 4, 40);
INSERT INTO product_in_stock (quantity, product_id, recommended_quantity) VALUES (0, 5, 0);

INSERT INTO stock_change (change, timestamp, product_id) VALUES (10, '2023-11-10 23:45:17.215199', 2);
INSERT INTO stock_change (change, timestamp, product_id) VALUES (10, '2023-11-11 00:05:25.526918', 2);
INSERT INTO stock_change (change, timestamp, product_id) VALUES (-10, '2023-11-11 00:05:29.900238', 2);
INSERT INTO stock_change (change, timestamp, product_id) VALUES (100, '2023-11-11 00:13:37.236458', 2);
INSERT INTO stock_change (change, timestamp, product_id) VALUES (-100, '2023-11-11 00:13:44.312590', 2);
INSERT INTO stock_change (change, timestamp, product_id) VALUES (10, '2023-11-11 11:16:35.403961', 2);
INSERT INTO stock_change (change, timestamp, product_id) VALUES (-10, '2023-11-11 11:16:42.729036', 2);
INSERT INTO stock_change (change, timestamp, product_id) VALUES (3, '2023-11-11 13:44:26.825841', 1);
INSERT INTO stock_change (change, timestamp, product_id) VALUES (-6, '2023-11-11 13:44:30.324836', 1);
INSERT INTO stock_change (change, timestamp, product_id) VALUES (10, '2023-11-11 15:39:40.702179', 1);
INSERT INTO stock_change (change, timestamp, product_id) VALUES (5, '2023-11-11 16:05:33.774344', 2);
INSERT INTO stock_change (change, timestamp, product_id) VALUES (3, '2023-11-11 16:05:33.774344', 1);
INSERT INTO stock_change (change, timestamp, product_id) VALUES (-5, '2023-11-11 16:08:20.505938', 2);
INSERT INTO stock_change (change, timestamp, product_id) VALUES (-3, '2023-11-11 16:08:20.505938', 1);
INSERT INTO stock_change (change, timestamp, product_id) VALUES (15, '2023-11-12 13:05:52.658333', 2);
INSERT INTO stock_change (change, timestamp, product_id) VALUES (10, '2023-11-12 13:28:18.177572', 2);