global:
  scrape_interval:   15s
  external_labels:
    monitor: 'client-service'

scrape_configs:
  - job_name: 'prometheus client-service'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8080']
      - labels:
          application : 'client-service'
