CREATE TABLE receipt(
    id int primary key generated by default as identity,
    actions varchar(255) not null ,
    title varchar(255) not null
);

CREATE TABLE recipe_productids_and_quantities(
    recipe_id int not null references receipt (id),
    productids_and_quantities int,
    productids_and_quantities_key int not null,
    constraint recipe_productids_and_quantities_pkey
        primary key (recipe_id, productids_and_quantities_key)
);

INSERT INTO receipt ( actions, title) VALUES ('Mix.', 'Salad');
INSERT INTO receipt ( actions, title) VALUES ('Just eat', 'Tomato and bread');
INSERT INTO receipt ( actions, title) VALUES ('Eat', 'Simple bread');

INSERT INTO recipe_productids_and_quantities (recipe_id, productids_and_quantities, productids_and_quantities_key) VALUES (1, 3, 1);
INSERT INTO recipe_productids_and_quantities (recipe_id, productids_and_quantities, productids_and_quantities_key) VALUES (1, 5, 2);
INSERT INTO recipe_productids_and_quantities (recipe_id, productids_and_quantities, productids_and_quantities_key) VALUES (2, 3, 2);
INSERT INTO recipe_productids_and_quantities (recipe_id, productids_and_quantities, productids_and_quantities_key) VALUES (2, 5, 3);






